# Generated by Django for recipe versioning.

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


def create_lineages_for_existing_recipes(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    RecipeLineage = apps.get_model("recipes", "RecipeLineage")
    for recipe in Recipe.objects.all().iterator():
        lineage = RecipeLineage.objects.create(slug=recipe.slug)
        recipe.lineage = lineage
        recipe.version_number = 1
        recipe.save(update_fields=["lineage", "version_number"])


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0007_lowercase_tag_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeLineage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["slug", "id"],
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="lineage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="recipes.recipelineage",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="version_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(create_lineages_for_existing_recipes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="recipe",
            name="lineage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="recipes.recipelineage",
            ),
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="slug",
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.UniqueConstraint(
                fields=("lineage", "version_number"),
                name="unique_recipe_version_per_lineage",
            ),
        ),
    ]
