# Generated by Django for collaborative recipe editing.

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_last_edited_by_from_owner(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    Recipe.objects.filter(last_edited_by__isnull=True, owner_id__isnull=False).update(
        last_edited_by_id=F("owner_id"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0008_recipe_versions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes_last_edited",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_last_edited_by_from_owner, migrations.RunPython.noop),
    ]
